### ISSUE TITLE
記事【PSでpeco】内コマンド記載に漏れがありました

### ISSUE THREAD

**Issue by linm25stg** [illumination-k/site#65]
記事【[Windows(Powershell)でpecoを使ってみる (履歴のインクリメンタルサーチ)](https://illumination-k.dev/techblog/post/432eaa6e-f795-4bf5-9f8d-443fd0c7e917)】内の**Powershellで履歴を得る**部分のコマンドに漏れがありました。
---

記事コード 
* `Get-Content (Get-PSReadlineOption).HistorySavePath | Select-Object -Unique`

正しく動作したコード 
* `Get-Content -Path (Get-PSReadlineOption).HistorySavePath | Select-Object -Unique`

問題箇所
---
![1](https://github.com/user-attachments/assets/5a308f2f-55ed-4709-90a1-d2bfe97b8ec8)

#### 記事コード を使用した場合
`Get-Content (Get-PSReadlineOption).HistorySavePath | Select-Object -Unique`
![2](https://github.com/user-attachments/assets/71acc83f-e680-4b66-9272-8b923dc0b84a)

#### 正しく動作したコード を使用した場合
`Get-Content -Path (Get-PSReadlineOption).HistorySavePath | Select-Object -Unique`
![3](https://github.com/user-attachments/assets/8841f8ba-652d-4364-985a-ac9754d6ffbd)

解決したキッカケ
---
記事内 __参考__ 一覧 [pocoで捗る日常生活](https://krymtkts.github.io/posts/2019-07-28-have-a-good-day-with-poco#:~:text=%E4%BD%9C%E3%81%A3%E3%81%9F%E9%96%A2%E6%95%B0%E3%81%AF%E4%BB%A5%E4%B8%8B%E3%81%AE%E9%80%9A%E3%82%8A%E3%80%82%E4%BC%BC%E3%81%9F%E3%82%88%E3%81%86%E3%81%AA%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%81%AFPSGallery%E3%81%AB%E4%BD%95%E5%80%8B%E3%81%8B%E3%81%82%E3%82%8B%E3%81%91%E3%81%A9%E3%80%81poco%E3%81%A7%E6%9B%B8%E3%81%8D%E3%81%9F%E3%81%8B%E3%81%A3%E3%81%9F%E3%81%AE%E3%81%A7%E8%87%AA%E4%BD%9C%E3%81%97%E3%81%9F%E6%AC%A1%E7%AC%AC%E3%80%82)

その他
---
記事内容がすごく助かりました、ありがとうございます!!
初めてissue機能を利用したので、使い方が誤っていた場合、ごめんなさい

**Comment by illumination-k** [comment]
#66 のPRで対応しました。ご報告ありがとうございます！
